version: '3.9'  # Верзија на Docker Compose која ја користиме

services:
  web:
    build: .  # Креираме слика за апликацијата врз основа на Dockerfile во моменталниот директориум
    ports:
      - "5000:5000"  # Мапира порта 5000 од контејнерот на порта 5000 на домашната машина
    environment:
      - FLASK_APP=app.py  # Определува која е главната Flask апликација (app.py)
      - FLASK_RUN_HOST=0.0.0.0  # Дозволува апликацијата да се слуша на сите мрежни интерфејси
    volumes:
      - ./templates:/app/templates  # Мапира локален директориум 'templates' на директориумот '/app/templates' во контејнерот
      - ./static:/app/static  # Мапира локален директориум 'static' на '/app/static' за статички фајлови
      - ./logs:/app/logs  # Мапира локален директориум 'logs' на '/app/logs' за лог фајлови
    networks:
      - app-network  # Ја поставува апликацијата во мрежата 'app-network'
    restart: unless-stopped  # Осигурува дека контејнерот ќе се рестартира ако се случи некоја грешка или ако е прекинат, освен ако не е рачно стопиран

networks:
  app-network:
    driver: bridge  # Создава мрежа со bridge тип кој дозволува контејнерите да комуницираат меѓусебно
